### ISSUE TITLE
Nothing show up in FE

### ISSUE THREAD

**Issue by heisenbol** [comvos/comvosfilelist#1]
I'm trying to use this extension, but for some reason nothing at all shows up in FE. I 've had problems like this in the past, that were always related with the caching mechanism. But with this extension nothing I've tried had any result. It is as if it never calls any code for the extension. I can move the pi1 folder to another location, and I don't get any error message.

I use typo3 4.7.7, comvosfilelist 1.0.2

I've attached a screenshot of my flexform configuration and a second one with the configuration of the extension. 

I don't have any typoscript setup. I just included the static template of the extension in my page.

Any help is appreciated

![flexform](https://f.cloud.github.com/assets/3510901/139257/f1dbc240-71e8-11e2-9c08-c1ec6e209486.png)
![ecxtconf](https://f.cloud.github.com/assets/3510901/139265/26091590-71e9-11e2-9c07-def7d595fe6c.png)

**Comment by nsaleh** [comment]
have you checked your typoscript configuration in the ts-object browser of the template module? Depending on how you handle your TS ( files, db, include css_styled_content stuff) plugin TS might be missing. 

Important:

```
tt_content.list.20.comvosfilelist_pi1 =<  plugin.tx_comvosfilelist_pi1
```

and plugin.tx_comvosfilelist_pi1 should be configured correctly too (untested)

```
plugin.tx_comvosfilelist_pi1 = USER
plugin.tx_comvosfilelist_pi1.includeLibs = typo3conf/ext/comvosfilelist/pi1/class.tx_comvosfilelist_pi1.php
plugin.tx_comvosfilelist_pi1.userFunc = tx_comvosfilelist_pi1->main
```

plugin.tx_comvosfilelist_pi1 should also contain the default plugin configuration if you included the default TS.

If this solves your problem please confirm, if it doesn't maby you can give me further information.

**Comment by heisenbol** [comment]
Thanks for the answer nsaleh. I'm not sure I can follow your suggestion:

I looked at the object browser and searched for comvosfilelist. I got only the following

```
[plugin]
    [tx_comvosfilelist_pi1]
        [entriesPerPage] = 30 # newsite page { #newsite includeCSS { #newsite univStyle= fileadmin/templates/v2/styles/university/css.css #newsite univStyle.title = all #newsite univStyle.media = all #newsite } #newsite }
        [useDAM] = false # fetch DAM-information from files
        [directory] = 
        [template] = default
        [cacheTwig] = 0
        [templateFolders]
```

So although I did include the static template that comes with comvosfilelist into my page's template, it doesn't show up in the obejct browser. So  I put your 2nd set of typoscript code into the setup section of my page. Again with no result.

Then I put also your 1st typoscript code into my setup section, and now I get an exception when I load the page. At least that is something.

```
Template not configured in TS "templateFolders": "default"
Exception thrown in file
/var/www/tuc/typo3conf/ext/comvosfilelist/pi1/class.tx_comvosfilelist_pi1.php in line 351.
```

Do I assume correctly that the static template I include does not do it's job?

**Comment by nsaleh** [comment]
Yes, the plugin is included correctly now but templatefolders are not configured by default. The templates shipped with the extension are more of an example and not included by default. I just reworked them and will add the secure demotemplate by default. You can checkout the latest version from github or just add the folowing to your TS-setup:

```
plugin.tx_comvosfilelist_pi1.templateFolders.default = typo3conf/ext/comvosfilelist/templates/secure
```

The new demo templates include some new stuff too ( SEO - metatags in singleview, relative css path). 
When checking it out from github remember: composer dependencies are not in the repository, so you have to install them with composer or just grab the vendor folder from the TER version you have.

I also added the TS-setting resulting from this issue in the default static TS.

**Comment by heisenbol** [comment]
I've added the TS configuration from your last message to my template. The error is now gone, and I get the filelist of my configured folder.

So for now it seems working.

Thank you for your help. I will test the new version you are preparing as soon as you upload it into the TER
