### ISSUE TITLE
baseurl is ignored

### ISSUE THREAD

**Issue by nurbs999** [comvos/comvosfilelist#3]
Hi

it seems that comvosfilelist ignores the baseurl setting of TYPO3. My baseurl points to subfolder inside my apache webroot. TYPO3 is handling it's urls quiet well, htaccess is setup correctly as mentioned by the extension and the docs, and in the extension-setup I also entered the correct host used to test fileprotection.
Still, in the frontend only the comvos extension tries to load it's css files relativ to the apache root instead of the TYPO3 root (set by baseurl)

e.g. http://192.168.0.38/typo3conf/ext/comvosfilelist/templates/css/comvosfilelist-default.css instead of http://192.168.0.38/my-project/typo3conf/ext/comvosfilelist/templates/css/comvosfilelist-default.css

**Comment by nsaleh** [comment]
Hi nurbs999,

right now I can't take care of this, I would recommend including the css by Typoscript for now or add it to your global site css (removing the include in the twig template). I'll leave the issue open and will fix this when i have some time to do so. Also you might want to have a look at getRelativeAssetPath in the twig extension 

https://github.com/comvos/comvosfilelist/blob/master/src/Comvos/TYPO3/Twig/Extension.php#L132 

You should be able to provide "absolute" paths? with the "includeJavascript" helper

regards Nabil

**Comment by nurbs999** [comment]
Adding the css is no problem. But the missing baseurl part screws all downloads for convosfilelist, including image- and thumb-paths.
Since I'm really in a hurry right now to get the extension ready for our side, I'll try to fix the bug it also.

**Comment by nsaleh** [comment]
ok, suggestion (untested): you have access to tsfe and the pluginconfiguration in twig ( "tsfe" and "conf" in twig) if your rewrites are adjusted for your subfolder configuration you might just do something like:
plugin.tx_comvosfilelist_pi1.pathPrefix= /subfolder/
href="{{ conf.pathPrefix }}+[thumbpath or filepath]"

**Comment by nsaleh** [comment]
Can this be closed, have you solved your problem?
